import Providers from "./Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["NextJs 13", "firebase", "crud", "React"],
  authors: [{ name: "Bright Odohofre" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
